name: agro_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0
  firebase_auth: ^0.14.0
  firebase_storage: ^3.0.4

  cupertino_icons: ^0.1.2
  charts_flutter: ^0.8.1
  syncfusion_flutter_charts: ^17.3.26

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets :
    - imagens/
